spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

server:
  port: 8300

eureka:
  instance:
    #网关所在的服务器域名
    hostname: "127.0.0.1"
  client:
    #是否将自己注册到 Eureka (服务需要将自己注册到 Eureka)
    register-with-eureka: true
    #是否从 Eureka 获取注册信息 (消费者需要从 Eureka 获取服务信息)
    fetch-registry: true
    service-url:
      #注册中心地址
      defaultZone: "http://127.0.0.1:8400/eureka/"