eureka:
  client:
    #是否将自己注册到 Eureka (服务需要将自己注册到 Eureka)
    register-with-eureka: false
    #是否从 Eureka 获取注册信息 (消费者需要从 Eureka 获取服务信息)
    fetch-registry: true
    service-url:
      #注册中心地址
      defaultZone: "http://eureka.domain.com:8400/eureka/"

logging:
  level:
    com.example.consumer: debug

feign:
  client:
    config:
      default:
        loggerLevel: full
