spring:
  application:
    name: "eureka"

server:
  port: 8400

eureka:
  client:
    #是否将自己注册到 Eureka (服务需要将自己注册到 Eureka)
    register-with-eureka: false
    #是否从 Eureka 获取注册信息 (消费者需要从 Eureka 获取服务信息)
    fetch-registry: false
    service-url:
      #注册中心地址
      defaultZone: "http://127.0.0.1:${server.port}/eureka/"